export type TApplicationDTO = {
  action: number;
  arch: string | null;
  bottom: boolean;
  common: boolean;
  commonApplication: boolean;
  configurations: any[];
  customerId: number;
  customerName: string;
  deletionProhibited: boolean;
  filePath: string | null;
  iconId: number | null;
  iconText: string | null;
  id: number;
  intent: string | null;
  latestVersion: number;
  latestVersionText: string | null;
  longTap: boolean;
  name: string;
  outdated: boolean;
  pkg: string;
  remove: boolean;
  runAfterInstall: boolean;
  runAtBoot: boolean;
  selected: boolean;
  showIcon: boolean;
  skipVersion: boolean;
  split: boolean;
  system: boolean;
  type: string;
  url: string | null;
  urlArm64: string | null;
  urlArmeabi: string | null;
  useKiosk: boolean;
  usedVersionId: number;
  version: string;
  versionCode: number;
  screenOrder: number | null;
  actionChanged?: boolean;
};
