import { TAppSettingsDTO } from './app-settings-dto.type';
import { TConfigurationFileDTO } from './configuration-file-dto.type';

export type TConfigurationDTO = {
  id?: number;
  name: string;
  description: string;
  password: string;
  type: number;
  applications: any[];
  customerId: number;
  autoUpdate: boolean;
  blockStatusBar: boolean;
  systemUpdateType: number;
  systemUpdateFrom: string | null;
  systemUpdateTo: string | null;
  scheduleAppUpdate: boolean;
  appUpdateFrom: string | null;
  appUpdateTo: string | null;
  downloadUpdates: string;
  gps: boolean | null;
  bluetooth: boolean | null;
  wifi: boolean | null;
  mobileData: boolean | null;
  usbStorage: boolean | null;
  requestUpdates: string;
  disableLocation: boolean;
  appPermissions: string;
  pushOptions: string;
  keepaliveTime: number;
  autoBrightness: boolean | null;
  brightness: number | null;
  manageTimeout: boolean;
  timeout: number | null;
  lockVolume: boolean;
  manageVolume: boolean;
  volume: number | null;
  passwordMode: string | null;
  orientation: number | null;
  runDefaultLauncher: boolean | null;
  disableScreenshots: boolean;
  autostartForeground: boolean;
  timeZone: string | null;
  allowedClasses: string | null;
  newServerUrl: string | null;
  lockSafeSettings: boolean | null;
  permissive: boolean;
  kioskExit: boolean;
  showWifi: boolean;
  mainAppId: number | null;
  eventReceivingComponent: string;
  kioskMode: boolean;
  contentAppId: number | null;
  wifiSSID: string;
  wifiPassword: string;
  wifiSecurityType: string | null;
  encryptDevice: boolean;
  qrParameters: string;
  mobileEnrollment: boolean;
  kioskHome: boolean;
  kioskRecents: boolean;
  kioskNotifications: boolean;
  kioskSystemInfo: boolean;
  kioskKeyguard: boolean;
  kioskLockButtons: boolean;
  kioskScreenOn: boolean;
  restrictions: string;
  useDefaultDesignSettings: boolean;
  backgroundColor: string | null;
  textColor: string | null;
  backgroundImageUrl: string | null;
  iconSize: string | null;
  desktopHeader: string | null;
  desktopHeaderTemplate: string | null;
  displayStatus: boolean;
  qrCodeKey: string;
  applicationUsageParameters: any | null;
  selected: boolean;
  baseUrl: string;
  filesToRemove: any[] | null;
  defaultFilePath: string;
  common: boolean;
  allowStatusBarExpansion: boolean;
  applicationSettings: TAppSettingsDTO[] | null;
  files: TConfigurationFileDTO[] | null;
};
