export const DEVICES_SORT_MAPPER: { [key: string]: string } = {
  statusCode: 'STATUS',
  lastUpdate: 'LAST_UPDATE',
  number: 'NUMBER',
  imei: 'IMEI',
  phone: 'PHONE',
  'info.model': 'MODEL',
  permissionStatus: 'PERMISSIONS',
  installationStatus: 'INSTALLATIONS',
  filesStatus: 'FILES',
  configurationId: 'CONFIGURATION',
  description: 'DESCRIPTION',
  group: 'GROUP',
  launcherVersion: 'LAUNCHER_VERSION',
  'info.batteryLevel': 'BATTERY_LEVEL',
  mdmMode: 'MDM_MODE',
  'info.defaultLauncher': 'DEFAULT_LAUNCHER',
  'info.kioskMode': 'KIOSK_MODE',
  androidVersion: 'ANDROID_VERSION',
  enrollTime: 'ENROLLMENT_DATE',
  serial: 'SERIAL',
  publicIp: 'PUBLICIP',
  custom1: 'CUSTOM1',
  custom2: 'CUSTOM2',
  custom3: 'CUSTOM3',
};
