export type TDevicesSettingsDTO = {
  id: number;
  customerId: number;
  roleId: number;
  columnDisplayedDeviceStatus: boolean | null;
  columnDisplayedDeviceDate: boolean | null;
  columnDisplayedDeviceNumber: boolean | null;
  columnDisplayedDeviceModel: boolean | null;
  columnDisplayedDevicePermissionsStatus: boolean | null;
  columnDisplayedDeviceAppInstallStatus: boolean | null;
  columnDisplayedDeviceFilesStatus: boolean | null;
  columnDisplayedDeviceConfiguration: boolean | null;
  columnDisplayedDeviceImei: boolean | null;
  columnDisplayedDevicePhone: boolean | null;
  columnDisplayedDeviceDesc: boolean | null;
  columnDisplayedDeviceGroup: boolean | null;
  columnDisplayedLauncherVersion: boolean | null;
  columnDisplayedBatteryLevel: boolean | null;
  columnDisplayedDefaultLauncher: boolean | null;
  columnDisplayedMdmMode: boolean | null;
  columnDisplayedKioskMode: boolean | null;
  columnDisplayedAndroidVersion: boolean | null;
  columnDisplayedEnrollmentDate: boolean | null;
  columnDisplayedSerial: boolean | null;
  columnDisplayedPublicIp: boolean | null;
  columnDisplayedCustom1: boolean | null;
  columnDisplayedCustom2: boolean | null;
  columnDisplayedCustom3: boolean | null;
  common: boolean;
};
