export type TSettingsDTO = {
  id: number;
  backgroundColor: string;
  textColor: string;
  backgroundImageUrl: string | null;
  iconSize: string;
  desktopHeader: string;
  desktopHeaderTemplate: string;
  customerId: number;
  useDefaultLanguage: boolean;
  language: string;
  createNewDevices: boolean;
  newDeviceGroupId: number | null;
  newDeviceConfigurationId: number | null;
  phoneNumberFormat: string;
  customPropertyName1: string;
  customPropertyName2: string;
  customPropertyName3: string;
  customMultiline1: boolean;
  customMultiline2: boolean;
  customMultiline3: boolean;
  customSend1: boolean;
  customSend2: boolean;
  customSend3: boolean;
  sendDescription: boolean;
  passwordReset: boolean;
  passwordLength: number;
  passwordStrength: number;
  twoFactor: boolean;
  idleLogout: number;
  singleCustomer: boolean;
  accountType: number;
  expiryTime: string | null;
  deviceLimit: number;
  deviceCount: number;
  sizeLimit: number;
  common: boolean;
};
